stages:
  # Run a command in the SSH env but don't wait, in case we disconnect
  # Or, maybe we wait, but the job continues to run, and if we run the
  # pipeline again, we'll resume here and wait for the result
  # The command can be
  #    nohub {cmd} &
  # Then we can periodically look for the existence of a file, signaling
  # that the job is done
  run-sim:
    cmd: calkit xenv -n cluster -- bash script.sh
    deps:
      - script.sh
    outs:
      - results.txt
