stages:
  # Run a command in the SSH 'cluster' env
  # Note that even if we disconnect while running, the results will be awaited
  # and collected if the pipeline is run again
  run-sim:
    cmd: calkit xenv -n cluster -- bash script.sh
    deps:
      - script.sh
    outs:
      - results:
          cache: false
